const C=HouseholdCore,$=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[],filename='RAW 파일을 불러와 주세요',result;
let filters={health:'all',screen:'all',golf:'all',free:'all'},freeMode='all';
const keys=['health','screen','golf','free'];
function eligible(c){return result.groups[c].filter(h=>c==='free'?(freeMode==='free'?h.freeDuplicate:freeMode==='mixed'?h.mixed:h.freeDuplicate||h.mixed):h.count>=2)}
function months(){const m=[...new Set(rows.map(r=>r.start.slice(0,7)).filter(Boolean))].sort().reverse();$('month').disabled=!m.length;if(!m.length){$('month').innerHTML='<option value="">파일 선택 후 표시</option>';return;}$('month').innerHTML=m.map(v=>`<option value="${v}">${v.slice(0,4)}년 ${Number(v.slice(5))}월</option>`).join('');}
function render(){result=C.analyze(rows,{month:$('month').value,excludeTest:$('exclude').checked});const s=result.stats;
 $('filename').textContent=filename;$('filemeta').textContent=`거래 ${rows.length.toLocaleString()}건 · 수강시작월 ${result.months.length}개`;
 $('overview').innerHTML=`<b>${esc($('month').selectedOptions[0]?.textContent||'')}</b> 기준 <b>다인원 ${keys.slice(0,3).reduce((n,c)=>n+result.groups[c].filter(h=>h.count>=2).length,0)}세대</b> <span class="muted">(시설별 합계)</span> · 무료 중복 확인 <b>${result.groups.free.filter(h=>h.freeDuplicate||h.mixed).length}세대</b>`;
 if(!rows.length){$('overview').textContent='RAW 매출 파일을 불러오면 시설별 집계와 동호수·회원명이 표시됩니다.';$('filemeta').textContent='XLS · XLSX · CSV / 최대 30MB';}
 $('dashboard').innerHTML=keys.map((c,i)=>panel(c,i)).join('');
 document.querySelectorAll('[data-group]').forEach(b=>b.addEventListener('click',()=>{filters[b.dataset.group]=b.dataset.value;render()}));
 const fm=$('free-mode');if(fm)fm.onchange=()=>{freeMode=fm.value;render()};
 $('stats').textContent=`999·9999동 ${s.test}건 · 환불 ${s.refunds}건 · 취소/비매출 ${s.cancel}건 · 전액 환불 원매출 ${s.voided}건 · 필수값 누락 ${s.missing}건 · 동일 회원 추가 등록 ${s.dedup}건 중복 제거`;
 $('review-count').textContent=result.review.length?`확인 필요 ${result.review.length}건`:'';
 $('excluded-products').innerHTML=`<p class="muted">대상 이용권 이외 ${s.unknown}건</p>`+result.unknown.map(p=>`<div class="product-row"><span>${esc(p.product)}</span><span>${p.count}건</span></div>`).join('');
 $('reviews').innerHTML=result.review.map(r=>`<div class="review-row">${esc(r.dong)}동 ${esc(r.ho)}호 · ${esc(r.name)}<br>${esc(r.product)}<br>${esc(r.reason)}</div>`).join('');
}
function panel(c,i){const all=eligible(c),data=all.filter(h=>filters[c]==='all'||(filters[c]==='4'?h.count>=4:h.count===Number(filters[c])));const allMembers=result.groups[c].reduce((n,h)=>n+h.count,0);
 const caption=c==='free'?`무료권 다인원 ${result.groups.free.filter(h=>h.freeDuplicate).length}세대 · 월권 병행 ${result.groups.free.filter(h=>h.mixed).length}세대`:`전체 등록 ${result.groups[c].length}세대 · ${allMembers}명`;
 return `<article class="panel ${c}"><div class="panel-head"><h2>${C.names[i]}</h2><div class="number">${all.length}<span>세대</span></div><p class="panel-caption">${caption}</p></div><div class="panel-body"><table class="summary-table"><thead><tr><th scope="col">구분</th><th scope="col">세대 수</th><th scope="col">총 인원</th></tr></thead><tbody>${[2,3,4].map(n=>{const a=all.filter(h=>n===4?h.count>=4:h.count===n);return `<tr><td>${n}명${n===4?' 이상':''}</td><td><b>${a.length}</b></td><td>${a.reduce((s,h)=>s+h.count,0)}</td></tr>`}).join('')}</tbody></table>${c==='free'?`<label class="segment-label" for="free-mode">확인 유형</label><select class="free-mode" id="free-mode">${[['all','전체 확인 대상'],['free','무료권 2명 이상'],['mixed','월권·무료권 병행']].map(([v,l])=>`<option value="${v}" ${freeMode===v?'selected':''}>${l}</option>`).join('')}</select>`:''}<p class="segment-label">등록 인원별 보기${c==='free'?' · 월권·무료권 합산':''}</p><div class="segments" aria-label="${C.names[i]} 인원 필터">${[['all','전체'],['2','2명'],['3','3명'],['4','4명 이상']].map(([v,l])=>`<button type="button" aria-pressed="${filters[c]===v}" class="${filters[c]===v?'active':''}" data-group="${c}" data-value="${v}">${l}</button>`).join('')}</div><div class="list-heading"><h3>동호수 · 회원 목록</h3><span>${data.length}세대</span></div><div class="households">${data.length?data.map(h=>`<div class="household"><div class="household-top"><span class="address">${esc(h.dong)}동 ${esc(h.ho)}호</span><span class="count">${h.count}명</span></div>${c==='free'?`<p class="kind">${esc(h.kind)}</p>`:''}<div class="members">${h.members.map(m=>`<div class="member-row"><span>${esc(m.name)}</span>${c==='free'?`<em>${esc(m.role)}</em>`:''}</div>`).join('')}</div>${c==='free'&&h.count===1?'<p class="kind">동일 회원의 월권·무료권 병행</p>':''}</div>`).join(''):`<div class="empty"><strong>해당 세대가 없어요</strong>${c==='free'?'선택한 유형·인원에 해당하는<br>무료 중복 내역이 없습니다.':'선택한 인원에 해당하는<br>다인원 등록 세대가 없습니다.'}</div>`}</div></div></article>`;
}
$('month').onchange=render;$('exclude').onchange=render;
$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('error').hidden=true;const label=document.querySelector('.upload-button');label.setAttribute('aria-busy','true');try{if(file.size>30*1024*1024)throw Error('30MB 이하 파일을 올려 주세요.');if(!/\.(xlsx?|csv)$/i.test(file.name))throw Error('XLS, XLSX 또는 CSV 파일을 선택해 주세요.');const buffer=await file.arrayBuffer();const book=XLSX.read(buffer,{type:'array',cellDates:false});let parsed,lastError;for(const name of book.SheetNames){try{parsed=C.parseGrid(XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,defval:'',raw:true}));break}catch(err){lastError=err}}if(!parsed)throw lastError||Error('읽을 수 있는 시트가 없어요.');if(!parsed.rows.some(r=>r.start))throw Error('유효한 수강시작일이 없어요.');rows=parsed.rows;filename=file.name;filters={health:'all',screen:'all',golf:'all',free:'all'};freeMode='all';months();render();}catch(err){$('error').textContent=`${err.message||'파일을 읽지 못했어요.'} 기존 집계는 유지됩니다.`;$('error').hidden=false;}finally{label.removeAttribute('aria-busy');e.target.value=''}};
months();render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_household_summary',title:'세대별 집계 조회',description:'현재 화면의 수강시작월 및 필터에 맞는 시설별 세대 수와 회원 목록을 조회합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(input&&Object.keys(input).length)throw Error('입력 항목이 필요하지 않습니다.');return {month:$('month').value,excludeTest:$('exclude').checked,groups:Object.fromEntries(keys.map(c=>[c,eligible(c).filter(h=>filters[c]==='all'||(filters[c]==='4'?h.count>=4:h.count===Number(filters[c]))).map(h=>({dong:h.dong,ho:h.ho,count:h.count,kind:h.kind||'',members:h.members.map(m=>({name:m.name,role:m.role||''}))}))]))}}})).catch(()=>{})}catch{}}
